import numpy as np 
l = [1,2,3,4]
t = (1,2,3,4)
al = np.array(l)
at = np.array(t)
print(al)
print(f'Type of al: {type(al)}')
print(f'shape of al: {al.shape}')
print(f'Size of al: {al.size}')
print(f'Dimention of al: {al.ndim}')
print(at)
print(f'Type of at: {type(at)}')
print(f'shape of at: {at.shape}')
print(f'Size of at: {at.size}')
print(f'Dimention of at: {at.ndim}')